<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            ["id"=>"1", "government_id"=>"1", "name"=>['en'=>"15 May" , 'ar'=>'"15 مايو"']],
            ["id"=>"2" ,"government_id"=>"1" ,"name"=>["ar"=>"الازبكية","en"=>"Al Azbakeyah"]],
            ["id"=>"3","government_id"=>"1","name"=>["ar"=>"البساتين","en"=>"Al Basatin"]],
            ["id"=>"4","government_id"=>"1","name"=>["ar"=>"التبين","en"=>"Tebin"]],
            ["id"=>"5","government_id"=>"1","name"=>["ar"=>"الخليفة","en"=>"El-Khalifa"]],
            ["id"=>"6","government_id"=>"1","name"=>["ar"=>"الدراسة","en"=>"El darrasa"]],
            ["id"=>"7","government_id"=>"1","name"=>["ar"=>"الدرب الاحمر","en"=>"Aldarb Alahmar"]],
            ["id"=>"8","government_id"=>"1","name"=>["ar"=>"الزاوية الحمراء","en"=>"Zawya al-Hamra"]],
            ["id"=>"9","government_id"=>"1","name"=>["ar"=>"الزيتون","en"=>"El-Zaytoun"]],
            ["id"=>"10","government_id"=>"1","name"=>["ar"=>"الساحل","en"=>"Sahel"]],
            ["id"=>"11","government_id"=>"1","name"=>["ar"=>"السلام","en"=>"El Salam"]],
            ["id"=>"12","government_id"=>"1","name"=>["ar"=>"السيدة زينب","en"=>"Sayeda Zeinab"]],
            ["id"=>"13","government_id"=>"1","name"=>["ar"=>"الشرابية","en"=>"El Sharabeya"]],
            ["id"=>"14","government_id"=>"1","name"=>["ar"=>"مدينة الشروق","en"=>"Shorouk"]],
            ["id"=>"15","government_id"=>"1","name"=>["ar"=>"الظاهر","en"=>"El Daher"]],
            ["id"=>"16","government_id"=>"1","name"=>["ar"=>"العتبة","en"=>"Ataba"]],
            ["id"=>"17","government_id"=>"1","name"=>["ar"=>"القاهرة الجديدة","en"=>"New Cairo"]],
            ["id"=>"18","government_id"=>"1","name"=>["ar"=>"المرج","en"=>"El Marg"]],
            ["id"=>"19","government_id"=>"1","name"=>["ar"=>"عزبة النخل","en"=>"Ezbet el Nakhl"]],
            ["id"=>"20","government_id"=>"1","name"=>["ar"=>"المطرية","en"=>"Matareya"]],
            ["id"=>"21","government_id"=>"1","name"=>["ar"=>"المعادى","en"=>"Maadi"]],
            ["id"=>"22","government_id"=>"1","name"=>["ar"=>"المعصرة","en"=>"Maasara"]],
            ["id"=>"23","government_id"=>"1","name"=>["ar"=>"المقطم","en"=>"Mokattam"]],
            ["id"=>"24","government_id"=>"1","name"=>["ar"=>"المنيل","en"=>"Manyal"]],
            ["id"=>"25","government_id"=>"1","name"=>["ar"=>"الموسكى","en"=>"Mosky"]],
            ["id"=>"26","government_id"=>"1","name"=>["ar"=>"النزهة","en"=>"Nozha"]],
            ["id"=>"27","government_id"=>"1","name"=>["ar"=>"الوايلى","en"=>"Waily"]],
            ["id"=>"28","government_id"=>"1","name"=>["ar"=>"باب الشعرية","en"=>"Bab al-Shereia"]],
            ["id"=>"29","government_id"=>"1","name"=>["ar"=>"بولاق","en"=>"Bolaq"]],
            ["id"=>"30","government_id"=>"1","name"=>["ar"=>"جاردن سيتى","en"=>"Garden City"]],
            ["id"=>"31","government_id"=>"1","name"=>["ar"=>"حدائق القبة","en"=>"Hadayek El-Kobba"]],
            ["id"=>"32","government_id"=>"1","name"=>["ar"=>"حلوان","en"=>"Helwan"]],
            ["id"=>"33","government_id"=>"1","name"=>["ar"=>"دار السلام","en"=>"Dar Al Salam"]],
            ["id"=>"34","government_id"=>"1","name"=>["ar"=>"شبرا","en"=>"Shubra"]],
            ["id"=>"35","government_id"=>"1","name"=>["ar"=>"طره","en"=>"Tura"]],
            ["id"=>"36","government_id"=>"1","name"=>["ar"=>"عابدين","en"=>"Abdeen"]],
            ["id"=>"37","government_id"=>"1","name"=>["ar"=>"عباسية","en"=>"Abaseya"]],
            ["id"=>"38","government_id"=>"1","name"=>["ar"=>"عين شمس","en"=>"Ain Shams"]],
            ["id"=>"39","government_id"=>"1","name"=>["ar"=>"مدينة نصر","en"=>"Nasr City"]],
            ["id"=>"40","government_id"=>"1","name"=>["ar"=>"مصر الجديدة","en"=>"New Heliopolis"]],
            ["id"=>"41","government_id"=>"1","name"=>["ar"=>"مصر القديمة","en"=>"Masr Al Qadima"]],
            ["id"=>"42","government_id"=>"1","name"=>["ar"=>"منشية ناصر","en"=>"Mansheya Nasir"]],
            ["id"=>"43","government_id"=>"1","name"=>["ar"=>"مدينة بدر","en"=>"Badr City"]],
            ["id"=>"44","government_id"=>"1","name"=>["ar"=>"مدينة العبور","en"=>"Obour City"]],
            ["id"=>"45","government_id"=>"1","name"=>["ar"=>"وسط البلد","en"=>"Cairo Downtown"]],
            ["id"=>"46","government_id"=>"1","name"=>["ar"=>"الزمالك","en"=>"Zamalek"]],
            ["id"=>"47","government_id"=>"1","name"=>["ar"=>"قصر النيل","en"=>"Kasr El Nile"]],
            ["id"=>"48","government_id"=>"1","name"=>["ar"=>"الرحاب","en"=>"Rehab"]],
            ["id"=>"49","government_id"=>"1","name"=>["ar"=>"القطامية","en"=>"Katameya"]],
            ["id"=>"50","government_id"=>"1","name"=>["ar"=>"مدينتي","en"=>"Madinty"]],
            ["id"=>"51","government_id"=>"1","name"=>["ar"=>"روض الفرج","en"=>"Rod Alfarag"]],
            ["id"=>"52","government_id"=>"1","name"=>["ar"=>"شيراتون","en"=>"Sheraton"]],
            ["id"=>"53","government_id"=>"1","name"=>["ar"=>"الجمالية","en"=>"El-Gamaleya"]],
            ["id"=>"54","government_id"=>"1","name"=>["ar"=>"العاشر من رمضان","en"=>"10th of Ramadan City"]],
            ["id"=>"55","government_id"=>"1","name"=>["ar"=>"الحلمية","en"=>"Helmeyat Alzaytoun"]],
            ["id"=>"56","government_id"=>"1","name"=>["ar"=>"النزهة الجديدة","en"=>"New Nozha"]],
            ["id"=>"57","government_id"=>"1","name"=>["ar"=>"العاصمة الإدارية","en"=>"Capital New"]],
            ["id"=>"58","government_id"=>"2","name"=>["ar"=>"الجيزة","en"=>"Giza"]],
            ["id"=>"59","government_id"=>"2","name"=>["ar"=>"السادس من أكتوبر","en"=>"Sixth of October"]],
            ["id"=>"60","government_id"=>"2","name"=>["ar"=>"الشيخ زايد","en"=>"Cheikh Zayed"]],
            ["id"=>"61","government_id"=>"2","name"=>["ar"=>"الحوامدية","en"=>"Hawamdiyah"]],
            ["id"=>"62","government_id"=>"2","name"=>["ar"=>"البدرشين","en"=>"Al Badrasheen"]],
            ["id"=>"63","government_id"=>"2","name"=>["ar"=>"الصف","en"=>"Saf"]],
            ["id"=>"64","government_id"=>"2","name"=>["ar"=>"أطفيح","en"=>"Atfih"]],
            ["id"=>"65","government_id"=>"2","name"=>["ar"=>"العياط","en"=>"Al Ayat"]],
            ["id"=>"66","government_id"=>"2","name"=>["ar"=>"الباويطي","en"=>"Al-Bawaiti"]],
            ["id"=>"67","government_id"=>"2","name"=>["ar"=>"منشأة القناطر","en"=>"ManshiyetAl Qanater"]],
            ["id"=>"68","government_id"=>"2","name"=>["ar"=>"أوسيم","en"=>"Oaseem"]],
            ["id"=>"69","government_id"=>"2","name"=>["ar"=>"كرداسة","en"=>"Kerdasa"]],
            ["id"=>"70","government_id"=>"2","name"=>["ar"=>"أبو النمرس","en"=>"Abu Nomros"]],
            ["id"=>"71","government_id"=>"2","name"=>["ar"=>"كفر غطاطي","en"=>"Kafr Ghati"]],
            ["id"=>"72","government_id"=>"2","name"=>["ar"=>"منشأة البكاري","en"=>"Manshiyet Al Bakari"]],
            ["id"=>"73","government_id"=>"2","name"=>["ar"=>"الدقى","en"=>"Dokki"]],
            ["id"=>"74","government_id"=>"2","name"=>["ar"=>"العجوزة","en"=>"Agouza"]],
            ["id"=>"75","government_id"=>"2","name"=>["ar"=>"الهرم","en"=>"Haram"]],
            ["id"=>"76","government_id"=>"2","name"=>["ar"=>"الوراق","en"=>"Warraq"]],
            ["id"=>"77","government_id"=>"2","name"=>["ar"=>"امبابة","en"=>"Imbaba"]],
            ["id"=>"78","government_id"=>"2","name"=>["ar"=>"بولاق الدكرور","en"=>"Boulaq Dakrour"]],
            ["id"=>"79","government_id"=>"2","name"=>["ar"=>"الواحات البحرية","en"=>"Al Wahat Al Baharia"]],
            ["id"=>"80","government_id"=>"2","name"=>["ar"=>"العمرانية","en"=>"Omraneya"]],
            ["id"=>"81","government_id"=>"2","name"=>["ar"=>"المنيب","en"=>"Moneeb"]],
            ["id"=>"82","government_id"=>"2","name"=>["ar"=>"بين السرايات","en"=>"Bin Alsarayat"]],
            ["id"=>"83","government_id"=>"2","name"=>["ar"=>"الكيت كات","en"=>"Kit Kat"]],
            ["id"=>"84","government_id"=>"2","name"=>["ar"=>"المهندسين","en"=>"Mohandessin"]],
            ["id"=>"85","government_id"=>"2","name"=>["ar"=>"فيصل","en"=>"Faisal"]],
            ["id"=>"86","government_id"=>"2","name"=>["ar"=>"أبو رواش","en"=>"Abu Rawash"]],
            ["id"=>"87","government_id"=>"2","name"=>["ar"=>"حدائق الأهرام","en"=>"Hadayek Alahram"]],
            ["id"=>"88","government_id"=>"2","name"=>["ar"=>"الحرانية","en"=>"Haraneya"]],
            ["id"=>"89","government_id"=>"2","name"=>["ar"=>"حدائق اكتوبر","en"=>"Hadayek October"]],
            ["id"=>"90","government_id"=>"2","name"=>["ar"=>"صفط اللبن","en"=>"Saft Allaban"]],
            ["id"=>"91","government_id"=>"2","name"=>["ar"=>"القرية الذكية","en"=>"Smart Village"]],
            ["id"=>"92","government_id"=>"2","name"=>["ar"=>"ارض اللواء","en"=>"Ard Ellwaa"]],
            ["id"=>"93","government_id"=>"3","name"=>["ar"=>"ابو قير","en"=>"Abu Qir"]],
            ["id"=>"94","government_id"=>"3","name"=>["ar"=>"الابراهيمية","en"=>"Al Ibrahimeyah"]],
            ["id"=>"95","government_id"=>"3","name"=>["ar"=>"الأزاريطة","en"=>"Azarita"]],
            ["id"=>"96","government_id"=>"3","name"=>["ar"=>"الانفوشى","en"=>"Anfoushi"]],
            ["id"=>"97","government_id"=>"3","name"=>["ar"=>"الدخيلة","en"=>"Dekheila"]],
            ["id"=>"98","government_id"=>"3","name"=>["ar"=>"السيوف","en"=>"El Soyof"]],
            ["id"=>"99","government_id"=>"3","name"=>["ar"=>"العامرية","en"=>"Ameria"]],
            ["id"=>"100","government_id"=>"3","name"=>["ar"=>"اللبان","en"=>"El Labban"]],
            ["id"=>"101","government_id"=>"3","name"=>["ar"=>"المفروزة","en"=>"Al Mafrouza"]],
            ["id"=>"102","government_id"=>"3","name"=>["ar"=>"المنتزه","en"=>"El Montaza"]],
            ["id"=>"103","government_id"=>"3","name"=>["ar"=>"المنشية","en"=>"Mansheya"]],
            ["id"=>"104","government_id"=>"3","name"=>["ar"=>"الناصرية","en"=>"Naseria"]],
            ["id"=>"105","government_id"=>"3","name"=>["ar"=>"امبروزو","en"=>"Ambrozo"]],
            ["id"=>"106","government_id"=>"3","name"=>["ar"=>"باب شرق","en"=>"Bab Sharq"]],
            ["id"=>"107","government_id"=>"3","name"=>["ar"=>"برج العرب","en"=>"Bourj Alarab"]],
            ["id"=>"108","government_id"=>"3","name"=>["ar"=>"ستانلى","en"=>"Stanley"]],
            ["id"=>"109","government_id"=>"3","name"=>["ar"=>"سموحة","en"=>"Smouha"]],
            ["id"=>"110","government_id"=>"3","name"=>["ar"=>"سيدى بشر","en"=>"Sidi Bishr"]],
            ["id"=>"111","government_id"=>"3","name"=>["ar"=>"شدس","en"=>"Shads"]],
            ["id"=>"112","government_id"=>"3","name"=>["ar"=>"غيط العنب","en"=>"Gheet Alenab"]],
            ["id"=>"113","government_id"=>"3","name"=>["ar"=>"فلمينج","en"=>"Fleming"]],
            ["id"=>"114","government_id"=>"3","name"=>["ar"=>"فيكتوريا","en"=>"Victoria"]],
            ["id"=>"115","government_id"=>"3","name"=>["ar"=>"كامب شيزار","en"=>"Camp Shizar"]],
            ["id"=>"116","government_id"=>"3","name"=>["ar"=>"كرموز","en"=>"Karmooz"]],
            ["id"=>"117","government_id"=>"3","name"=>["ar"=>"محطة الرمل","en"=>"Mahta Alraml"]],
            ["id"=>"118","government_id"=>"3","name"=>["ar"=>"مينا البصل","en"=>"Mina El-Basal"]],
            ["id"=>"119","government_id"=>"3","name"=>["ar"=>"العصافرة","en"=>"Asafra"]],
            ["id"=>"120","government_id"=>"3","name"=>["ar"=>"العجمي","en"=>"Agamy"]],
            ["id"=>"121","government_id"=>"3","name"=>["ar"=>"بكوس","en"=>"Bakos"]],
            ["id"=>"122","government_id"=>"3","name"=>["ar"=>"بولكلي","en"=>"Boulkly"]],
            ["id"=>"123","government_id"=>"3","name"=>["ar"=>"كليوباترا","en"=>"Cleopatra"]],
            ["id"=>"124","government_id"=>"3","name"=>["ar"=>"جليم","en"=>"Glim"]],
            ["id"=>"125","government_id"=>"3","name"=>["ar"=>"المعمورة","en"=>"Al Mamurah"]],
            ["id"=>"126","government_id"=>"3","name"=>["ar"=>"المندرة","en"=>"Al Mandara"]],
            ["id"=>"127","government_id"=>"3","name"=>["ar"=>"محرم بك","en"=>"Moharam Bek"]],
            ["id"=>"128","government_id"=>"3","name"=>["ar"=>"الشاطبي","en"=>"Elshatby"]],
            ["id"=>"129","government_id"=>"3","name"=>["ar"=>"سيدي جابر","en"=>"Sidi Gaber"]],
            ["id"=>"130","government_id"=>"3","name"=>["ar"=>"الساحل الشمالي","en"=>"North Coast\/sahel"]],
            ["id"=>"131","government_id"=>"3","name"=>["ar"=>"الحضرة","en"=>"Alhadra"]],
            ["id"=>"132","government_id"=>"3","name"=>["ar"=>"العطارين","en"=>"Alattarin"]],
            ["id"=>"133","government_id"=>"3","name"=>["ar"=>"سيدي كرير","en"=>"Sidi Kerir"]],
            ["id"=>"134","government_id"=>"3","name"=>["ar"=>"الجمرك","en"=>"Elgomrok"]],
            ["id"=>"135","government_id"=>"3","name"=>["ar"=>"المكس","en"=>"Al Max"]],
            ["id"=>"137","government_id"=>"4","name"=>["ar"=>"المنصورة","en"=>"Mansoura"]],
            ["id"=>"138","government_id"=>"4","name"=>["ar"=>"طلخا","en"=>"Talkha"]],
            ["id"=>"139","government_id"=>"4","name"=>["ar"=>"ميت غمر","en"=>"Mitt Ghamr"]],
            ["id"=>"140","government_id"=>"4","name"=>["ar"=>"دكرنس","en"=>"Dekernes"]],
            ["id"=>"141","government_id"=>"4","name"=>["ar"=>"أجا","en"=>"Aga"]],
            ["id"=>"142","government_id"=>"4","name"=>["ar"=>"منية النصر","en"=>"Menia El Nasr"]],
            ["id"=>"143","government_id"=>"4","name"=>["ar"=>"السنبلاوين","en"=>"Sinbillawin"]],
            ["id"=>"144","government_id"=>"4","name"=>["ar"=>"الكردي","en"=>"El Kurdi"]],
            ["id"=>"145","government_id"=>"4","name"=>["ar"=>"بني عبيد","en"=>"Bani Ubaid"]],
            ["id"=>"146","government_id"=>"4","name"=>["ar"=>"المنزلة","en"=>"Al Manzala"]],
            ["id"=>"147","government_id"=>"4","name"=>["ar"=>"تمي الأمديد","en"=>"tami al'amdid"]],
            ["id"=>"148","government_id"=>"4","name"=>["ar"=>"الجمالية","en"=>"aljamalia"]],
            ["id"=>"149","government_id"=>"4","name"=>["ar"=>"شربين","en"=>"Sherbin"]],
            ["id"=>"150","government_id"=>"4","name"=>["ar"=>"المطرية","en"=>"Mataria"]],
            ["id"=>"151","government_id"=>"4","name"=>["ar"=>"بلقاس","en"=>"Belqas"]],
            ["id"=>"152","government_id"=>"4","name"=>["ar"=>"ميت سلسيل","en"=>"Meet Salsil"]],
            ["id"=>"153","government_id"=>"4","name"=>["ar"=>"جمصة","en"=>"Gamasa"]],
            ["id"=>"154","government_id"=>"4","name"=>["ar"=>"محلة دمنة","en"=>"Mahalat Damana"]],
            ["id"=>"155","government_id"=>"4","name"=>["ar"=>"نبروه","en"=>"Nabroh"]],
            ["id"=>"156","government_id"=>"5","name"=>["ar"=>"الغردقة","en"=>"Hurghada"]],
            ["id"=>"157","government_id"=>"5","name"=>["ar"=>"رأس غارب","en"=>"Ras Ghareb"]],
            ["id"=>"158","government_id"=>"5","name"=>["ar"=>"سفاجا","en"=>"Safaga"]],
            ["id"=>"159","government_id"=>"5","name"=>["ar"=>"القصير","en"=>"El Qusiar"]],
            ["id"=>"160","government_id"=>"5","name"=>["ar"=>"مرسى علم","en"=>"Marsa Alam"]],
            ["id"=>"161","government_id"=>"5","name"=>["ar"=>"الشلاتين","en"=>"Shalatin"]],
            ["id"=>"162","government_id"=>"5","name"=>["ar"=>"حلايب","en"=>"Halaib"]],
            ["id"=>"163","government_id"=>"5","name"=>["ar"=>"الدهار","en"=>"Aldahar"]],
            ["id"=>"164","government_id"=>"6","name"=>["ar"=>"دمنهور","en"=>"Damanhour"]],
            ["id"=>"165","government_id"=>"6","name"=>["ar"=>"كفر الدوار","en"=>"Kafr El Dawar"]],
            ["id"=>"166","government_id"=>"6","name"=>["ar"=>"رشيد","en"=>"Rashid"]],
            ["id"=>"167","government_id"=>"6","name"=>["ar"=>"إدكو","en"=>"Edco"]],
            ["id"=>"168","government_id"=>"6","name"=>["ar"=>"أبو المطامير","en"=>"Abu al-Matamir"]],
            ["id"=>"169","government_id"=>"6","name"=>["ar"=>"أبو حمص","en"=>"Abu Homs"]],
            ["id"=>"170","government_id"=>"6","name"=>["ar"=>"الدلنجات","en"=>"Delengat"]],
            ["id"=>"171","government_id"=>"6","name"=>["ar"=>"المحمودية","en"=>"Mahmoudiyah"]],
            ["id"=>"172","government_id"=>"6","name"=>["ar"=>"الرحمانية","en"=>"Rahmaniyah"]],
            ["id"=>"173","government_id"=>"6","name"=>["ar"=>"إيتاي البارود","en"=>"Itai Baroud"]],
            ["id"=>"174","government_id"=>"6","name"=>["ar"=>"حوش عيسى","en"=>"Housh Eissa"]],
            ["id"=>"175","government_id"=>"6","name"=>["ar"=>"شبراخيت","en"=>"Shubrakhit"]],
            ["id"=>"176","government_id"=>"6","name"=>["ar"=>"كوم حمادة","en"=>"Kom Hamada"]],
            ["id"=>"177","government_id"=>"6","name"=>["ar"=>"بدر","en"=>"Badr"]],
            ["id"=>"178","government_id"=>"6","name"=>["ar"=>"وادي النطرون","en"=>"Wadi Natrun"]],
            ["id"=>"179","government_id"=>"6","name"=>["ar"=>"النوبارية الجديدة","en"=>"New Nubaria"]],
            ["id"=>"180","government_id"=>"6","name"=>["ar"=>"النوبارية","en"=>"Alnoubareya"]],
            ["id"=>"181","government_id"=>"7","name"=>["ar"=>"الفيوم","en"=>"Fayoum"]],
            ["id"=>"182","government_id"=>"7","name"=>["ar"=>"الفيوم الجديدة","en"=>"Fayoum El Gedida"]],
            ["id"=>"183","government_id"=>"7","name"=>["ar"=>"طامية","en"=>"Tamiya"]],
            ["id"=>"184","government_id"=>"7","name"=>["ar"=>"سنورس","en"=>"Snores"]],
            ["id"=>"185","government_id"=>"7","name"=>["ar"=>"إطسا","en"=>"Etsa"]],
            ["id"=>"186","government_id"=>"7","name"=>["ar"=>"إبشواي","en"=>"Epschway"]],
            ["id"=>"187","government_id"=>"7","name"=>["ar"=>"يوسف الصديق","en"=>"Yusuf El Sediaq"]],
            ["id"=>"188","government_id"=>"7","name"=>["ar"=>"الحادقة","en"=>"Hadqa"]],
            ["id"=>"189","government_id"=>"7","name"=>["ar"=>"اطسا","en"=>"Atsa"]],
            ["id"=>"190","government_id"=>"7","name"=>["ar"=>"الجامعة","en"=>"Algamaa"]],
            ["id"=>"191","government_id"=>"7","name"=>["ar"=>"السيالة","en"=>"Sayala"]],
            ["id"=>"192","government_id"=>"8","name"=>["ar"=>"طنطا","en"=>"Tanta"]],
            ["id"=>"193","government_id"=>"8","name"=>["ar"=>"المحلة الكبرى","en"=>"Al Mahalla Al Kobra"]],
            ["id"=>"194","government_id"=>"8","name"=>["ar"=>"كفر الزيات","en"=>"Kafr El Zayat"]],
            ["id"=>"195","government_id"=>"8","name"=>["ar"=>"زفتى","en"=>"Zefta"]],
            ["id"=>"196","government_id"=>"8","name"=>["ar"=>"السنطة","en"=>"El Santa"]],
            ["id"=>"197","government_id"=>"8","name"=>["ar"=>"قطور","en"=>"Qutour"]],
            ["id"=>"198","government_id"=>"8","name"=>["ar"=>"بسيون","en"=>"Basion"]],
            ["id"=>"199","government_id"=>"8","name"=>["ar"=>"سمنود","en"=>"Samannoud"]],
            ["id"=>"200","government_id"=>"9","name"=>["ar"=>"الإسماعيلية","en"=>"Ismailia"]],
            ["id"=>"201","government_id"=>"9","name"=>["ar"=>"فايد","en"=>"Fayed"]],
            ["id"=>"202","government_id"=>"9","name"=>["ar"=>"القنطرة شرق","en"=>"Qantara Sharq"]],
            ["id"=>"203","government_id"=>"9","name"=>["ar"=>"القنطرة غرب","en"=>"Qantara Gharb"]],
            ["id"=>"204","government_id"=>"9","name"=>["ar"=>"التل الكبير","en"=>"El Tal El Kabier"]],
            ["id"=>"205","government_id"=>"9","name"=>["ar"=>"أبو صوير","en"=>"Abu Sawir"]],
            ["id"=>"206","government_id"=>"9","name"=>["ar"=>"القصاصين الجديدة","en"=>"Kasasien El Gedida"]],
            ["id"=>"207","government_id"=>"9","name"=>["ar"=>"نفيشة","en"=>"Nefesha"]],
            ["id"=>"208","government_id"=>"9","name"=>["ar"=>"الشيخ زايد","en"=>"Sheikh Zayed"]],
            ["id"=>"209","government_id"=>"10","name"=>["ar"=>"شبين الكوم","en"=>"Shbeen El Koom"]],
            ["id"=>"210","government_id"=>"10","name"=>["ar"=>"مدينة السادات","en"=>"Sadat City"]],
            ["id"=>"211","government_id"=>"10","name"=>["ar"=>"منوف","en"=>"Menouf"]],
            ["id"=>"212","government_id"=>"10","name"=>["ar"=>"سرس الليان","en"=>"Sars El-Layan"]],
            ["id"=>"213","government_id"=>"10","name"=>["ar"=>"أشمون","en"=>"Ashmon"]],
            ["id"=>"214","government_id"=>"10","name"=>["ar"=>"الباجور","en"=>"Al Bagor"]],
            ["id"=>"215","government_id"=>"10","name"=>["ar"=>"قويسنا","en"=>"Quesna"]],
            ["id"=>"216","government_id"=>"10","name"=>["ar"=>"بركة السبع","en"=>"Berkat El Saba"]],
            ["id"=>"217","government_id"=>"10","name"=>["ar"=>"تلا","en"=>"Tala"]],
            ["id"=>"218","government_id"=>"10","name"=>["ar"=>"الشهداء","en"=>"Al Shohada"]],
            ["id"=>"219","government_id"=>"11","name"=>["ar"=>"المنيا","en"=>"Minya"]],
            ["id"=>"220","government_id"=>"11","name"=>["ar"=>"المنيا الجديدة","en"=>"Minya El Gedida"]],
            ["id"=>"221","government_id"=>"11","name"=>["ar"=>"العدوة","en"=>"El Adwa"]],
            ["id"=>"222","government_id"=>"11","name"=>["ar"=>"مغاغة","en"=>"Magagha"]],
            ["id"=>"223","government_id"=>"11","name"=>["ar"=>"بني مزار","en"=>"Bani Mazar"]],
            ["id"=>"224","government_id"=>"11","name"=>["ar"=>"مطاي","en"=>"Mattay"]],
            ["id"=>"225","government_id"=>"11","name"=>["ar"=>"سمالوط","en"=>"Samalut"]],
            ["id"=>"226","government_id"=>"11","name"=>["ar"=>"المدينة الفكرية","en"=>"Madinat El Fekria"]],
            ["id"=>"227","government_id"=>"11","name"=>["ar"=>"ملوي","en"=>"Meloy"]],
            ["id"=>"228","government_id"=>"11","name"=>["ar"=>"دير مواس","en"=>"Deir Mawas"]],
            ["id"=>"229","government_id"=>"11","name"=>["ar"=>"ابو قرقاص","en"=>"Abu Qurqas"]],
            ["id"=>"230","government_id"=>"11","name"=>["ar"=>"ارض سلطان","en"=>"Ard Sultan"]],
            ["id"=>"231","government_id"=>"12","name"=>["ar"=>"بنها","en"=>"Banha"]],
            ["id"=>"232","government_id"=>"12","name"=>["ar"=>"قليوب","en"=>"Qalyub"]],
            ["id"=>"233","government_id"=>"12","name"=>["ar"=>"شبرا الخيمة","en"=>"Shubra Al Khaimah"]],
            ["id"=>"234","government_id"=>"12","name"=>["ar"=>"القناطر الخيرية","en"=>"Al Qanater Charity"]],
            ["id"=>"235","government_id"=>"12","name"=>["ar"=>"الخانكة","en"=>"Khanka"]],
            ["id"=>"236","government_id"=>"12","name"=>["ar"=>"كفر شكر","en"=>"Kafr Shukr"]],
            ["id"=>"237","government_id"=>"12","name"=>["ar"=>"طوخ","en"=>"Tukh"]],
            ["id"=>"238","government_id"=>"12","name"=>["ar"=>"قها","en"=>"Qaha"]],
            ["id"=>"239","government_id"=>"12","name"=>["ar"=>"العبور","en"=>"Obour"]],
            ["id"=>"240","government_id"=>"12","name"=>["ar"=>"الخصوص","en"=>"Khosous"]],
            ["id"=>"241","government_id"=>"12","name"=>["ar"=>"شبين القناطر","en"=>"Shibin Al Qanater"]],
            ["id"=>"242","government_id"=>"12","name"=>["ar"=>"مسطرد","en"=>"Mostorod"]],
            ["id"=>"243","government_id"=>"13","name"=>["ar"=>"الخارجة","en"=>"El Kharga"]],
            ["id"=>"244","government_id"=>"13","name"=>["ar"=>"باريس","en"=>"Paris"]],
            ["id"=>"245","government_id"=>"13","name"=>["ar"=>"موط","en"=>"Mout"]],
            ["id"=>"246","government_id"=>"13","name"=>["ar"=>"الفرافرة","en"=>"Farafra"]],
            ["id"=>"247","government_id"=>"13","name"=>["ar"=>"بلاط","en"=>"Balat"]],
            ["id"=>"248","government_id"=>"13","name"=>["ar"=>"الداخلة","en"=>"Dakhla"]],
            ["id"=>"249","government_id"=>"14","name"=>["ar"=>"السويس","en"=>"Suez"]],
            ["id"=>"250","government_id"=>"14","name"=>["ar"=>"الجناين","en"=>"Alganayen"]],
            ["id"=>"251","government_id"=>"14","name"=>["ar"=>"عتاقة","en"=>"Ataqah"]],
            ["id"=>"252","government_id"=>"14","name"=>["ar"=>"العين السخنة","en"=>"Ain Sokhna"]],
            ["id"=>"253","government_id"=>"14","name"=>["ar"=>"فيصل","en"=>"Faysal"]],
            ["id"=>"254","government_id"=>"15","name"=>["ar"=>"أسوان","en"=>"Aswan"]],
            ["id"=>"255","government_id"=>"15","name"=>["ar"=>"أسوان الجديدة","en"=>"Aswan El Gedida"]],
            ["id"=>"256","government_id"=>"15","name"=>["ar"=>"دراو","en"=>"Drau"]],
            ["id"=>"257","government_id"=>"15","name"=>["ar"=>"كوم أمبو","en"=>"Kom Ombo"]],
            ["id"=>"258","government_id"=>"15","name"=>["ar"=>"نصر النوبة","en"=>"Nasr Al Nuba"]],
            ["id"=>"259","government_id"=>"15","name"=>["ar"=>"كلابشة","en"=>"Kalabsha"]],
            ["id"=>"260","government_id"=>"15","name"=>["ar"=>"إدفو","en"=>"Edfu"]],
            ["id"=>"261","government_id"=>"15","name"=>["ar"=>"الرديسية","en"=>"Al-Radisiyah"]],
            ["id"=>"262","government_id"=>"15","name"=>["ar"=>"البصيلية","en"=>"Al Basilia"]],
            ["id"=>"263","government_id"=>"15","name"=>["ar"=>"السباعية","en"=>"Al Sibaeia"]],
            ["id"=>"264","government_id"=>"15","name"=>["ar"=>"ابوسمبل السياحية","en"=>"Abo Simbl Al Siyahia"]],
            ["id"=>"266","government_id"=>"16","name"=>["ar"=>"أسيوط","en"=>"Assiut"]],
            ["id"=>"267","government_id"=>"16","name"=>["ar"=>"أسيوط الجديدة","en"=>"Assiut El Gedida"]],
            ["id"=>"268","government_id"=>"16","name"=>["ar"=>"ديروط","en"=>"Dayrout"]],
            ["id"=>"269","government_id"=>"16","name"=>["ar"=>"منفلوط","en"=>"Manfalut"]],
            ["id"=>"270","government_id"=>"16","name"=>["ar"=>"القوصية","en"=>"Qusiya"]],
            ["id"=>"271","government_id"=>"16","name"=>["ar"=>"أبنوب","en"=>"Abnoub"]],
            ["id"=>"272","government_id"=>"16","name"=>["ar"=>"أبو تيج","en"=>"Abu Tig"]],
            ["id"=>"273","government_id"=>"16","name"=>["ar"=>"الغنايم","en"=>"El Ghanaim"]],
            ["id"=>"274","government_id"=>"16","name"=>["ar"=>"ساحل سليم","en"=>"Sahel Selim"]],
            ["id"=>"275","government_id"=>"16","name"=>["ar"=>"البداري","en"=>"El Badari"]],
            ["id"=>"276","government_id"=>"16","name"=>["ar"=>"صدفا","en"=>"Sidfa"]],
            ["id"=>"277","government_id"=>"17","name"=>["ar"=>"بني سويف","en"=>"Bani Sweif"]],
            ["id"=>"278","government_id"=>"17","name"=>["ar"=>"بني سويف الجديدة","en"=>"Beni Suef El Gedida"]],
            ["id"=>"279","government_id"=>"17","name"=>["ar"=>"الواسطى","en"=>"Al Wasta"]],
            ["id"=>"280","government_id"=>"17","name"=>["ar"=>"ناصر","en"=>"Naser"]],
            ["id"=>"281","government_id"=>"17","name"=>["ar"=>"إهناسيا","en"=>"Ehnasia"]],
            ["id"=>"282","government_id"=>"17","name"=>["ar"=>"ببا","en"=>"beba"]],
            ["id"=>"283","government_id"=>"17","name"=>["ar"=>"الفشن","en"=>"Fashn"]],
            ["id"=>"284","government_id"=>"17","name"=>["ar"=>"سمسطا","en"=>"Somasta"]],
            ["id"=>"285","government_id"=>"17","name"=>["ar"=>"الاباصيرى","en"=>"Alabbaseri"]],
            ["id"=>"286","government_id"=>"17","name"=>["ar"=>"مقبل","en"=>"Mokbel"]],
            ["id"=>"287","government_id"=>"18","name"=>["ar"=>"بورسعيد","en"=>"PorSaid"]],
            ["id"=>"288","government_id"=>"18","name"=>["ar"=>"بورفؤاد","en"=>"Port Fouad"]],
            ["id"=>"289","government_id"=>"18","name"=>["ar"=>"العرب","en"=>"Alarab"]],
            ["id"=>"290","government_id"=>"18","name"=>["ar"=>"حى الزهور","en"=>"Zohour"]],
            ["id"=>"291","government_id"=>"18","name"=>["ar"=>"حى الشرق","en"=>"Alsharq"]],
            ["id"=>"292","government_id"=>"18","name"=>["ar"=>"حى الضواحى","en"=>"Aldawahi"]],
            ["id"=>"293","government_id"=>"18","name"=>["ar"=>"حى المناخ","en"=>"Almanakh"]],
            ["id"=>"294","government_id"=>"18","name"=>["ar"=>"حى مبارك","en"=>"Mubarak"]],
            ["id"=>"295","government_id"=>"19","name"=>["ar"=>"دمياط","en"=>"Damietta"]],
            ["id"=>"296","government_id"=>"19","name"=>["ar"=>"دمياط الجديدة","en"=>"New Damietta"]],
            ["id"=>"297","government_id"=>"19","name"=>["ar"=>"رأس البر","en"=>"Ras El Bar"]],
            ["id"=>"298","government_id"=>"19","name"=>["ar"=>"فارسكور","en"=>"Faraskour"]],
            ["id"=>"299","government_id"=>"19","name"=>["ar"=>"الزرقا","en"=>"Zarqa"]],
            ["id"=>"300","government_id"=>"19","name"=>["ar"=>"السرو","en"=>"alsaru"]],
            ["id"=>"301","government_id"=>"19","name"=>["ar"=>"الروضة","en"=>"alruwda"]],
            ["id"=>"302","government_id"=>"19","name"=>["ar"=>"كفر البطيخ","en"=>"Kafr El-Batikh"]],
            ["id"=>"303","government_id"=>"19","name"=>["ar"=>"عزبة البرج","en"=>"Azbet Al Burg"]],
            ["id"=>"304","government_id"=>"19","name"=>["ar"=>"ميت أبو غالب","en"=>"Meet Abou Ghalib"]],
            ["id"=>"305","government_id"=>"19","name"=>["ar"=>"كفر سعد","en"=>"Kafr Saad"]],
            ["id"=>"306","government_id"=>"20","name"=>["ar"=>"الزقازيق","en"=>"Zagazig"]],
            ["id"=>"307","government_id"=>"20","name"=>["ar"=>"العاشر من رمضان","en"=>"Al Ashr Men Ramadan"]],
            ["id"=>"308","government_id"=>"20","name"=>["ar"=>"منيا القمح","en"=>"Minya Al Qamh"]],
            ["id"=>"309","government_id"=>"20","name"=>["ar"=>"بلبيس","en"=>"Belbeis"]],
            ["id"=>"310","government_id"=>"20","name"=>["ar"=>"مشتول السوق","en"=>"Mashtoul El Souq"]],
            ["id"=>"311","government_id"=>"20","name"=>["ar"=>"القنايات","en"=>"Qenaiat"]],
            ["id"=>"312","government_id"=>"20","name"=>["ar"=>"أبو حماد","en"=>"Abu Hammad"]],
            ["id"=>"313","government_id"=>"20","name"=>["ar"=>"القرين","en"=>"El Qurain"]],
            ["id"=>"314","government_id"=>"20","name"=>["ar"=>"ههيا","en"=>"Hehia"]],
            ["id"=>"315","government_id"=>"20","name"=>["ar"=>"أبو كبير","en"=>"Abu Kabir"]],
            ["id"=>"316","government_id"=>"20","name"=>["ar"=>"فاقوس","en"=>"Faccus"]],
            ["id"=>"317","government_id"=>"20","name"=>["ar"=>"الصالحية الجديدة","en"=>"El Salihia El Gedida"]],
            ["id"=>"318","government_id"=>"20","name"=>["ar"=>"الإبراهيمية","en"=>"Al Ibrahimiyah"]],
            ["id"=>"319","government_id"=>"20","name"=>["ar"=>"ديرب نجم","en"=>"Deirb Negm"]],
            ["id"=>"320","government_id"=>"20","name"=>["ar"=>"كفر صقر","en"=>"Kafr Saqr"]],
            ["id"=>"321","government_id"=>"20","name"=>["ar"=>"أولاد صقر","en"=>"Awlad Saqr"]],
            ["id"=>"322","government_id"=>"20","name"=>["ar"=>"الحسينية","en"=>"Husseiniya"]],
            ["id"=>"323","government_id"=>"20","name"=>["ar"=>"صان الحجر القبلية","en"=>"san alhajar alqablia"]],
            ["id"=>"324","government_id"=>"20","name"=>["ar"=>"منشأة أبو عمر","en"=>"Manshayat Abu Omar"]],
            ["id"=>"325","government_id"=>"21","name"=>["ar"=>"الطور","en"=>"Al Toor"]],
            ["id"=>"326","government_id"=>"21","name"=>["ar"=>"شرم الشيخ","en"=>"Sharm El-Shaikh"]],
            ["id"=>"327","government_id"=>"21","name"=>["ar"=>"دهب","en"=>"Dahab"]],
            ["id"=>"328","government_id"=>"21","name"=>["ar"=>"نويبع","en"=>"Nuweiba"]],
            ["id"=>"329","government_id"=>"21","name"=>["ar"=>"طابا","en"=>"Taba"]],
            ["id"=>"330","government_id"=>"21","name"=>["ar"=>"سانت كاترين","en"=>"Saint Catherine"]],
            ["id"=>"331","government_id"=>"21","name"=>["ar"=>"أبو رديس","en"=>"Abu Redis"]],
            ["id"=>"332","government_id"=>"21","name"=>["ar"=>"أبو زنيمة","en"=>"Abu Zenaima"]],
            ["id"=>"333","government_id"=>"21","name"=>["ar"=>"رأس سدر","en"=>"Ras Sidr"]],
            ["id"=>"334","government_id"=>"22","name"=>["ar"=>"كفر الشيخ","en"=>"Kafr El Sheikh"]],
            ["id"=>"335","government_id"=>"22","name"=>["ar"=>"وسط البلد كفر الشيخ","en"=>"Kafr El Sheikh Downtown"]],
            ["id"=>"336","government_id"=>"22","name"=>["ar"=>"دسوق","en"=>"Desouq"]],
            ["id"=>"337","government_id"=>"22","name"=>["ar"=>"فوه","en"=>"Fooh"]],
            ["id"=>"338","government_id"=>"22","name"=>["ar"=>"مطوبس","en"=>"Metobas"]],
            ["id"=>"339","government_id"=>"22","name"=>["ar"=>"برج البرلس","en"=>"Burg Al Burullus"]],
            ["id"=>"340","government_id"=>"22","name"=>["ar"=>"بلطيم","en"=>"Baltim"]],
            ["id"=>"341","government_id"=>"22","name"=>["ar"=>"مصيف بلطيم","en"=>"Masief Baltim"]],
            ["id"=>"342","government_id"=>"22","name"=>["ar"=>"الحامول","en"=>"Hamol"]],
            ["id"=>"343","government_id"=>"22","name"=>["ar"=>"بيلا","en"=>"Bella"]],
            ["id"=>"344","government_id"=>"22","name"=>["ar"=>"الرياض","en"=>"Riyadh"]],
            ["id"=>"345","government_id"=>"22","name"=>["ar"=>"سيدي سالم","en"=>"Sidi Salm"]],
            ["id"=>"346","government_id"=>"22","name"=>["ar"=>"قلين","en"=>"Qellen"]],
            ["id"=>"347","government_id"=>"22","name"=>["ar"=>"سيدي غازي","en"=>"Sidi Ghazi"]],
            ["id"=>"348","government_id"=>"23","name"=>["ar"=>"مرسى مطروح","en"=>"Marsa Matrouh"]],
            ["id"=>"349","government_id"=>"23","name"=>["ar"=>"الحمام","en"=>"El Hamam"]],
            ["id"=>"350","government_id"=>"23","name"=>["ar"=>"العلمين","en"=>"Alamein"]],
            ["id"=>"351","government_id"=>"23","name"=>["ar"=>"الضبعة","en"=>"Dabaa"]],
            ["id"=>"352","government_id"=>"23","name"=>["ar"=>"النجيلة","en"=>"Al-Nagila"]],
            ["id"=>"353","government_id"=>"23","name"=>["ar"=>"سيدي براني","en"=>"Sidi Brani"]],
            ["id"=>"354","government_id"=>"23","name"=>["ar"=>"السلوم","en"=>"Salloum"]],
            ["id"=>"355","government_id"=>"23","name"=>["ar"=>"سيوة","en"=>"Siwa"]],
            ["id"=>"356","government_id"=>"23","name"=>["ar"=>"مارينا","en"=>"Marina"]],
            ["id"=>"357","government_id"=>"23","name"=>["ar"=>"الساحل الشمالى","en"=>"North Coast"]],
            ["id"=>"358","government_id"=>"24","name"=>["ar"=>"الأقصر","en"=>"Luxor"]],
            ["id"=>"359","government_id"=>"24","name"=>["ar"=>"الأقصر الجديدة","en"=>"New Luxor"]],
            ["id"=>"360","government_id"=>"24","name"=>["ar"=>"إسنا","en"=>"Esna"]],
            ["id"=>"361","government_id"=>"24","name"=>["ar"=>"طيبة الجديدة","en"=>"New Tiba"]],
            ["id"=>"362","government_id"=>"24","name"=>["ar"=>"الزينية","en"=>"Al ziynia"]],
            ["id"=>"363","government_id"=>"24","name"=>["ar"=>"البياضية","en"=>"Al Bayadieh"]],
            ["id"=>"364","government_id"=>"24","name"=>["ar"=>"القرنة","en"=>"Al Qarna"]],
            ["id"=>"365","government_id"=>"24","name"=>["ar"=>"أرمنت","en"=>"Armant"]],
            ["id"=>"366","government_id"=>"24","name"=>["ar"=>"الطود","en"=>"Al Tud"]],
            ["id"=>"367","government_id"=>"25","name"=>["ar"=>"قنا","en"=>"Qena"]],
            ["id"=>"368","government_id"=>"25","name"=>["ar"=>"قنا الجديدة","en"=>"New Qena"]],
            ["id"=>"369","government_id"=>"25","name"=>["ar"=>"ابو طشت","en"=>"Abu Tesht"]],
            ["id"=>"370","government_id"=>"25","name"=>["ar"=>"نجع حمادي","en"=>"Nag Hammadi"]],
            ["id"=>"371","government_id"=>"25","name"=>["ar"=>"دشنا","en"=>"Deshna"]],
            ["id"=>"372","government_id"=>"25","name"=>["ar"=>"الوقف","en"=>"Alwaqf"]],
            ["id"=>"373","government_id"=>"25","name"=>["ar"=>"قفط","en"=>"Qaft"]],
            ["id"=>"374","government_id"=>"25","name"=>["ar"=>"نقادة","en"=>"Naqada"]],
            ["id"=>"375","government_id"=>"25","name"=>["ar"=>"فرشوط","en"=>"Farshout"]],
            ["id"=>"376","government_id"=>"25","name"=>["ar"=>"قوص","en"=>"Quos"]],
            ["id"=>"377","government_id"=>"26","name"=>["ar"=>"العريش","en"=>"Arish"]],
            ["id"=>"378","government_id"=>"26","name"=>["ar"=>"الشيخ زويد","en"=>"Sheikh Zowaid"]],
            ["id"=>"379","government_id"=>"26","name"=>["ar"=>"نخل","en"=>"Nakhl"]],
            ["id"=>"380","government_id"=>"26","name"=>["ar"=>"رفح","en"=>"Rafah"]],
            ["id"=>"381","government_id"=>"26","name"=>["ar"=>"بئر العبد","en"=>"Bir al-Abed"]],
            ["id"=>"382","government_id"=>"26","name"=>["ar"=>"الحسنة","en"=>"Al Hasana"]],
            ["id"=>"383","government_id"=>"27","name"=>["ar"=>"سوهاج","en"=>"Sohag"]],
            ["id"=>"384","government_id"=>"27","name"=>["ar"=>"سوهاج الجديدة","en"=>"Sohag El Gedida"]],
            ["id"=>"385","government_id"=>"27","name"=>["ar"=>"أخميم","en"=>"Akhmeem"]],
            ["id"=>"386","government_id"=>"27","name"=>["ar"=>"أخميم الجديدة","en"=>"Akhmim El Gedida"]],
            ["id"=>"387","government_id"=>"27","name"=>["ar"=>"البلينا","en"=>"Albalina"]],
            ["id"=>"388","government_id"=>"27","name"=>["ar"=>"المراغة","en"=>"El Maragha"]],
            ["id"=>"389","government_id"=>"27","name"=>["ar"=>"المنشأة","en"=>"almunsha'a"]],
            ["id"=>"390","government_id"=>"27","name"=>["ar"=>"دار السلام","en"=>"Dar AISalaam"]],
            ["id"=>"391","government_id"=>"27","name"=>["ar"=>"جرجا","en"=>"Gerga"]],
            ["id"=>"392","government_id"=>"27","name"=>["ar"=>"جهينة الغربية","en"=>"Jahina Al Gharbia"]],
            ["id"=>"393","government_id"=>"27","name"=>["ar"=>"ساقلته","en"=>"Saqilatuh"]],
            ["id"=>"394","government_id"=>"27","name"=>["ar"=>"طما","en"=>"Tama"]],
            ["id"=>"395","government_id"=>"27","name"=>["ar"=>"طهطا","en"=>"Tahta"]],
            ["id"=>"396","government_id"=>"27","name"=>["ar"=>"الكوثر","en"=>"Alkawthar"]]
        ];
        foreach ($cities as $key => $city) {
            City::create($city);
        }

    }
}
